version: '3'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
    expose:
      - 3001
    ports:
      - "3001:3001"

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
